services:
  portrait-server:
    image: portrait-server
    hostname: portrait
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./www:/home/damo/www
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
