version: "3.8"

services:
  portrait-server:
    env_file:
      - .env
    image: portrait-server
    hostname: portrait
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./www:/home/damo/www
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    environment:
      ROCKET_PORT: 8000
      ROCKET_ADDRESS: 0.0.0.0
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    restart: unless-stopped
